!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE OBJECTIVE_FUNCTION_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  USE COMPUTE_FORCE_COEFFS_MOD_DIFF
  USE COMPUTE_ENTROPY_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of objective_function in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: total_enstrophy
!   with respect to varying inputs: *(point.prim)
!   Plus diff mem management of: point.prim:in
  SUBROUTINE OBJECTIVE_FUNCTION_D()
    IMPLICIT NONE
! call compute_cl_cd_cm()
! call compute_entropy()
    CALL COMPUTE_ENSTROPHY_D()
  END SUBROUTINE OBJECTIVE_FUNCTION_D

  SUBROUTINE OBJECTIVE_FUNCTION()
    IMPLICIT NONE
! call compute_cl_cd_cm()
! call compute_entropy()
    CALL COMPUTE_ENSTROPHY()
  END SUBROUTINE OBJECTIVE_FUNCTION

END MODULE OBJECTIVE_FUNCTION_MOD_DIFF

