1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (TC20) Variable rank is not declared
7 q_lskum: (TC33) External procedure update_begin_phi1_ghost is not declared
8 q_lskum: (TC33) External procedure update_end_phi1_ghost is not declared
9 q_lskum: (TC33) External procedure update_begin_phi2_ghost is not declared
10 q_lskum: (TC33) External procedure update_end_phi2_ghost is not declared
11 q_lskum: (TC33) External procedure ieee_is_nan is not declared
12 q_lskum: (DF03) variable rank is used before initialized
13 q_lskum: (DF03) variable rank is used before initialized
14 q_lskum: (DF03) variable rank is used before initialized
15 q_lskum: (DF03) variable rank is used before initialized
16 (DF05) External routine ieee_is_nan, called by (q_lskum), is assumed default In:.1. and Out:.11
17 (DF05) External routine update_end_phi2_ghost, called by (q_lskum), is assumed default In:. and Out:.
18 (DF05) External routine update_begin_phi2_ghost, called by (q_lskum), is assumed default In:. and Out:.
19 (DF05) External routine update_end_phi1_ghost, called by (q_lskum), is assumed default In:. and Out:.
20 (DF05) External routine update_begin_phi1_ghost, called by (q_lskum), is assumed default In:. and Out:.
21 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
22 fpi_solver_mod: (DD15) Module stagnation_values_mod is not defined
23 fpi_solver: (TC33) External procedure update_begin_dq_ghost is not declared
24 fpi_solver: (TC33) External procedure update_begin_qm_ghost is not declared
25 fpi_solver: (TC33) External procedure update_end_dq_ghost is not declared
26 fpi_solver: (TC33) External procedure update_end_qm_ghost is not declared
27 fpi_solver: (TC33) External procedure update_begin_ddq_ghost is not declared
28 fpi_solver: (TC33) External procedure update_end_ddq_ghost is not declared
29 fpi_solver: (TC33) External procedure update_begin_prim_ghost is not declared
30 fpi_solver: (TC33) External procedure update_end_prim_ghost is not declared
31 fpi_solver: (TC20) Variable rank is not declared
32 fpi_solver: (TC33) External procedure print_primal_output is not declared
33 fpi_solver: (DF03) variable rank is used before initialized
34 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
35 (DF05) External routine update_end_prim_ghost, called by (fpi_solver), is assumed default In:. and Out:.
36 (DF05) External routine update_begin_prim_ghost, called by (fpi_solver), is assumed default In:. and Out:.
37 (DF05) External routine update_end_ddq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
38 (DF05) External routine update_begin_ddq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
39 (DF05) External routine update_end_qm_ghost, called by (fpi_solver), is assumed default In:. and Out:.
40 (DF05) External routine update_end_dq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
41 (DF05) External routine update_begin_qm_ghost, called by (fpi_solver), is assumed default In:. and Out:.
42 (DF05) External routine update_begin_dq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
43 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
44 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
45 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
46 get_interior_neighbours: (TC20) Variable rank is not declared
47 get_interior_neighbours: (DF03) variable rank is used before initialized
48 get_interior_neighbours: (DF03) variable rank is used before initialized
49 get_interior_neighbours: (DF03) variable rank is used before initialized
50 get_interior_neighbours: (DF03) variable rank is used before initialized
51 get_wall_boundary_neighbours: (TC20) Variable rank is not declared
52 get_wall_boundary_neighbours: (DF03) variable rank is used before initialized
53 get_wall_boundary_neighbours: (DF03) variable rank is used before initialized
54 get_wall_boundary_neighbours: (DF03) variable rank is used before initialized
55 get_outer_boundary_neighbours: (TC20) Variable rank is not declared
56 get_outer_boundary_neighbours: (DF03) variable rank is used before initialized
57 get_outer_boundary_neighbours: (DF03) variable rank is used before initialized
58 get_outer_boundary_neighbours: (DF03) variable rank is used before initialized
59 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
60 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
61 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
62 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
63 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
64 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
65 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
66 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
67 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
68 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
69 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
70 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
71 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
72 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
73 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
74 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
75 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
76 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
77 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
78 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
79 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
80 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
81 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
82 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
83 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
84 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
85 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
86 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
87 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
88 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
89 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
90 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
91 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
92 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
93 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
94 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
95 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
96 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
97 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
98 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
99 flux_gxp: (TC33) External procedure derf is not declared
100 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
101 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
102 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
103 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
104 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
105 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
106 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
107 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
108 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
109 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
110 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
111 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
112 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
113 compute_cl_cd_cm: (TC20) Variable proc is not declared
114 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
115 compute_cl_cd_cm: (TC20) Variable rank is not declared
116 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
117 compute_entropy: (TC20) Variable mpi_double is not declared
118 compute_entropy: (TC20) Variable mpi_sum is not declared
119 compute_entropy: (TC20) Variable petsc_comm_world is not declared
120 compute_entropy: (TC20) Variable ierr is not declared
121 compute_entropy: (TC20) Variable rank is not declared
122 compute_enstrophy: (TC20) Variable rank is not declared
123 compute_enstrophy: (DF03) variable rank is used before initialized
124 compute_enstrophy: (DF03) variable gtotal_enstrophy is used before initialized
125 get_interior_neighbours: Tool: (TypeSpec tree regeneration) null wrapped type
126 get_wall_boundary_neighbours: Tool: (TypeSpec tree regeneration) null wrapped type
127 get_outer_boundary_neighbours: Tool: (TypeSpec tree regeneration) null wrapped type
128 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
